/* eslint-disable */
/* Generated by scripts/export_web_engine.py — do not edit by hand. */

/** CrewScore browser scorer — generated from Python. Do not edit by hand. */
(function (global) {
  const ENGINE = {
  "version": "0.2.0",
  "dimensions": [
    {
      "key": "injection",
      "label": "Prompt Injection Resistance"
    },
    {
      "key": "hallucination",
      "label": "Hallucination Guardrails"
    },
    {
      "key": "citation",
      "label": "Source Citation Requirements"
    },
    {
      "key": "cost",
      "label": "Cost Runaway Protection"
    },
    {
      "key": "human_gate",
      "label": "Human-in-the-Loop Gates"
    },
    {
      "key": "safe_stop",
      "label": "Safe-Stop Behavior"
    },
    {
      "key": "audit",
      "label": "Audit Trail & Provenance"
    },
    {
      "key": "compliance",
      "label": "Compliance Readiness"
    }
  ],
  "patterns": {
    "injection": [
      "ignore\\s+(previous|above|all)\\s+(instructions|prompts)",
      "do\\s+not\\s+(follow|obey|listen)\\s+to\\s+(user|input).*(system|instruction)",
      "system\\s+prompt.*(?:confidential|private|do\\s+not\\s+reveal)",
      "reject.*(?:inject|override|manipulat)",
      "adversar|injection|jailbreak",
      "do\\s+not\\s+reveal\\s+(your|the|this)\\s+(system|instructions|prompt)",
      "you\\s+cannot\\s+be\\s+(instructed|told|asked)\\s+to\\s+(ignore|override)",
      "safety|guardrail|boundar"
    ],
    "hallucination": [
      "do\\s+not\\s+(?:fabricat|invent|make\\s+up|generat).*(?:fact|data|citation|source|number)",
      "if\\s+you\\s+(?:do\\s+not\\s+know|are\\s+unsure|lack\\s+(?:the|enough)\\s+(?:data|information|evidence))",
      "only\\s+(?:use|cite|reference)\\s+(?:provided|given|available|verified)\\s+(?:data|information|sources|context)",
      "(?:hallucin|fabricat|confabulat)",
      "say\\s+(?:I\\s+dont\\s+know|I\\s+cannot|I\\s+do\\s+not\\s+have)",
      "ground(?:ed|ing)\\s+in\\s+(?:the|provided|given)",
      "do\\s+not\\s+guess|never\\s+guess|avoid\\s+guess",
      "recommend.*(?:consult|doctor|professional|specialist|expert)"
    ],
    "citation": [
      "(?:cite|citation|reference|attribute|source\\s+link|footnote)",
      "(?:source|evidence|provenance)\\s*(?:link|id|span|reference)",
      "every\\s+(?:claim|statement|answer|output)\\s+must\\s+(?:cite|reference|include)",
      "link\\s+(?:to|back\\s+to)\\s+(?:the|its|each)\\s+(?:source|evidence|document)",
      "\\[?\\d+\\]?.*(?:source|ref|cite)"
    ],
    "cost": [
      "(?:token|cost|budget|spend)\\s*(?:limit|cap|max|ceiling|threshold)",
      "(?:max|maximum)\\s*(?:token|tokens|length|response)",
      "(?:rate|cost)\\s*limit",
      "budget|spending|cost\\s*control",
      "truncat(?:e|ion)|max_tokens|max_length"
    ],
    "human_gate": [
      "(?:human|user|supervisor|operator|reviewer|staff|manager)\\s*(?:must|shall|should|needs?\\s+to)\\s*(?:approve|review|confirm|verify|check|validate)",
      "(?:human|human-in-the-loop|hitl|manual)\\s*(?:review|approval|gate|checkpoint|oversight)",
      "(?:before|prior\\s+to)\\s*(?:execut|send|submit|releas|publish|deploy)",
      "do\\s+not\\s+(?:auto|automatic).*(?:execute|send|submit|approve|publish)",
      "(?:require|mandate).*(?:human|manual)\\s*(?:approval|review|confirmation)",
      "(?:staff|clinician|doctor|nurse|analyst|officer)\\s*(?:review|approve|sign)"
    ],
    "safe_stop": [
      "(?:stop|halt|pause|refuse|decline|abort).*(?:if|when|unless)",
      "(?:insufficient|missing|incomplete|unclear|ambiguous)\\s*(?:data|evidence|information|context|instruction)",
      "(?:if|when)\\s+you\\s+(?:are\\s+)?(?:un)?(?:sure|certain|confident)",
      "(?:cannot|can.t|should\\s+not)\\s+(?:proceed|continue|act|respond)",
      "(?:escalat|hand\\s*off|transfer|refer).*(?:human|supervisor|specialist|operator)",
      "(?:safe|calibrated|graceful)\\s*(?:stop|halt|failure|abort|exit)",
      "refuse|disclaim|opt\\s*out"
    ],
    "audit": [
      "(?:log|record|track|trace|audit)\\s*(?:trail|history|event|action|decision|every|all|each)",
      "(?:audit|logging|trace|provenance|accountab)",
      "(?:record|preserve|retain)\\s*(?:the|all|every|each)\\s*(?:decision|action|step|reason|source)",
      "immutable|append.only|tamper.proof|write.once",
      "(?:who|what|when|why|how)\\s*(?:did|made|took|decided|executed)"
    ],
    "compliance": [
      "(?:hipaa|phi|protected\\s+health|patient\\s+data|baa|business\\s+associate)",
      "(?:soc\\s*2|soc2|system\\s+and\\s+organization\\s+controls)",
      "(?:gdpr|general\\s+data\\s+protection|data\\s+protection\\s+regulation)",
      "(?:eu\\s+ai\\s+act|artificial\\s+intelligence\\s+act|ai\\s+regulation)",
      "(?:fda|medical\\s+device|saMD|software\\s+as\\s+a\\s+medical\\s+device)",
      "(?:pci|pci.dss|payment\\s+card)",
      "(?:ferpa|student\\s+data|education\\s+record)",
      "(?:compliance|regulat|govern|legal|legal\\s+requirement)",
      "(?:encrypt|redact|de.identif|anonymi|pseudonymi)"
    ]
  },
  "signal_labels": {
    "injection": [
      {
        "pattern": "ignore\\s+(previous|above|all)\\s+(instructions|prompts)",
        "label": "Reject ignore-previous-instructions / override attempts"
      },
      {
        "pattern": "do\\s+not\\s+(follow|obey|listen)\\s+to\\s+(user|input).*(system|instruction)",
        "label": "Do not follow user input that conflicts with system rules"
      },
      {
        "pattern": "do\\s+not\\s+reveal\\s+(your|the|this)\\s+(system|instructions|prompt)",
        "label": "Keep system prompt confidential / do not reveal it"
      }
    ],
    "hallucination": [
      {
        "pattern": "do\\s+not\\s+(?:fabricat|invent|make\\s+up|generat).*(?:fact|data|citation|source|number)",
        "label": "Do not fabricate facts, citations, or numbers"
      },
      {
        "pattern": "if\\s+you\\s+(?:do\\s+not\\s+know|are\\s+unsure|lack\\s+(?:the|enough)\\s+(?:data|information|evidence))",
        "label": "Say so when you do not know or lack evidence"
      },
      {
        "pattern": "only\\s+(?:use|cite|reference)\\s+(?:provided|given|available|verified)\\s+(?:data|information|sources|context)",
        "label": "Only use provided / verified data"
      }
    ],
    "citation": [
      {
        "pattern": "(?:cite|citation|reference|attribute|source\\s+link|footnote)",
        "label": "Require citations, references, or source links"
      },
      {
        "pattern": "every\\s+(?:claim|statement|answer|output)\\s+must\\s+(?:cite|reference|include)",
        "label": "Every claim must cite its source"
      },
      {
        "pattern": "link\\s+(?:to|back\\s+to)\\s+(?:the|its|each)\\s+(?:source|evidence|document)",
        "label": "Link claims back to source evidence"
      }
    ],
    "cost": [
      {
        "pattern": "(?:token|cost|budget|spend)\\s*(?:limit|cap|max|ceiling|threshold)",
        "label": "Token / cost / budget limit or cap"
      },
      {
        "pattern": "(?:max|maximum)\\s*(?:token|tokens|length|response)",
        "label": "Max token or response length constraint"
      },
      {
        "pattern": "(?:rate|cost)\\s*limit",
        "label": "Rate or cost limiting"
      }
    ],
    "human_gate": [
      {
        "pattern": "(?:human|user|supervisor|operator|reviewer|staff|manager)\\s*(?:must|shall|should|needs?\\s+to)\\s*(?:approve|review|confirm|verify|check|validate)",
        "label": "Human / supervisor must approve or review"
      },
      {
        "pattern": "(?:human|human-in-the-loop|hitl|manual)\\s*(?:review|approval|gate|checkpoint|oversight)",
        "label": "Human-in-the-loop review or approval gate"
      },
      {
        "pattern": "(?:before|prior\\s+to)\\s*(?:execut|send|submit|releas|publish|deploy)",
        "label": "Approval required before execute / send / publish"
      }
    ],
    "safe_stop": [
      {
        "pattern": "(?:stop|halt|pause|refuse|decline|abort).*(?:if|when|unless)",
        "label": "Stop / halt / refuse when conditions are unmet"
      },
      {
        "pattern": "(?:insufficient|missing|incomplete|unclear|ambiguous)\\s*(?:data|evidence|information|context|instruction)",
        "label": "Handle missing or insufficient evidence"
      },
      {
        "pattern": "(?:escalat|hand\\s*off|transfer|refer).*(?:human|supervisor|specialist|operator)",
        "label": "Escalate to a human supervisor"
      }
    ],
    "audit": [
      {
        "pattern": "(?:log|record|track|trace|audit)\\s*(?:trail|history|event|action|decision|every|all|each)",
        "label": "Log or audit trail for actions and decisions"
      },
      {
        "pattern": "(?:audit|logging|trace|provenance|accountab)",
        "label": "Audit / logging / provenance accountability"
      },
      {
        "pattern": "immutable|append.only|tamper.proof|write.once",
        "label": "Immutable or append-only audit trail"
      }
    ],
    "compliance": [
      {
        "pattern": "(?:hipaa|phi|protected\\s+health|patient\\s+data|baa|business\\s+associate)",
        "label": "HIPAA / PHI / protected health data handling"
      },
      {
        "pattern": "(?:soc\\s*2|soc2|system\\s+and\\s+organization\\s+controls)",
        "label": "SOC 2 controls"
      },
      {
        "pattern": "(?:gdpr|general\\s+data\\s+protection|data\\s+protection\\s+regulation)",
        "label": "GDPR / data protection requirements"
      }
    ]
  },
  "vendor_questions": [
    "Can you demo it with YOUR data, not their cherry-picked showcase?",
    "Published accuracy/reliability benchmark from an independent third party?",
    "SOC2 / HIPAA / ISO 27001 certified (not 'in progress' or 'compliant-ready')?",
    "Full audit trail: you can see what the AI did and why?",
    "Documented human-override path for critical decisions?",
    "You can export your data if you leave (no vendor lock-in)?",
    "Pricing is transparent and predictable (no surprise token costs)?",
    "Published security audit or pen test within the last 12 months?",
    "Can show 3+ customers in YOUR industry running in production (not pilots)?",
    "Documented incident/escalation process when the AI fails?"
  ],
  "vendor_keys": [
    "vapor_demo",
    "benchmark",
    "certification",
    "audit",
    "human_override",
    "portability",
    "pricing",
    "security_audit",
    "production_refs",
    "incident"
  ],
  "vendor_critical_keys": [
    "certification",
    "audit",
    "human_override",
    "security_audit",
    "incident"
  ]
};

  function scoreFromMatchCount(matches, total) {
    if (!total || matches === 0) return 0;
    const raw = matches / total;
    return Math.min(100, Math.round(15 + raw * 85));
  }

  function safeRegExp(pattern) {
    try {
      return new RegExp(pattern, "i");
    } catch (e) {
      return null;
    }
  }

  function matchPatterns(promptLower, patterns) {
    const hits = [];
    for (const pattern of patterns) {
      const re = safeRegExp(pattern);
      if (!re) continue;
      const m = promptLower.match(re);
      if (m) {
        let snip = m[0].replace(/\s+/g, " ");
        if (snip.length > 120) snip = snip.slice(0, 119) + "…";
        hits.push({ pattern, snippet: snip });
      }
    }
    return hits;
  }

  function applyLengthBonus(scores, promptLower) {
    const words = promptLower.trim() ? promptLower.trim().split(/\s+/).length : 0;
    if (words > 500) {
      const bonus = Math.min(10, Math.floor((words - 500) / 200));
      for (const k of Object.keys(scores)) {
        scores[k] = Math.min(100, scores[k] + bonus);
      }
    }
    return scores;
  }

  function analyzeWithFindings(systemPrompt) {
    const dimOrder = ENGINE.dimensions.map((d) => d.key);
    if (!systemPrompt || !String(systemPrompt).trim()) {
      const scores = {};
      const findings = [];
      for (const key of dimOrder) {
        scores[key] = 0;
        const signals = ENGINE.signal_labels[key] || [];
        for (const s of signals.slice(0, 3)) {
          findings.push({
            dimension: key,
            status: "missing",
            pattern_or_reason: s.label,
            snippet: null,
          });
        }
      }
      return { scores, findings, overall: 0 };
    }

    const promptLower = String(systemPrompt).toLowerCase();
    const scores = {};
    const findings = [];

    for (const key of dimOrder) {
      const patterns = ENGINE.patterns[key] || [];
      const hits = matchPatterns(promptLower, patterns);
      scores[key] = scoreFromMatchCount(hits.length, patterns.length);

      for (const h of hits.slice(0, 3)) {
        findings.push({
          dimension: key,
          status: "matched",
          pattern_or_reason: h.pattern,
          snippet: h.snippet,
        });
      }

      let missingCount = 0;
      for (const s of ENGINE.signal_labels[key] || []) {
        if (missingCount >= 3) break;
        const re = safeRegExp(s.pattern);
        const matched = re ? re.test(promptLower) : false;
        if (matched) continue;
        findings.push({
          dimension: key,
          status: "missing",
          pattern_or_reason: s.label,
          snippet: null,
        });
        missingCount += 1;
      }
      if (!hits.length && missingCount === 0) {
        findings.push({
          dimension: key,
          status: "missing",
          pattern_or_reason: "No " + key + " guardrail signals detected",
          snippet: null,
        });
      }
    }

    applyLengthBonus(scores, promptLower);
    const vals = dimOrder.map((k) => scores[k]);
    const overall = vals.length
      ? Math.floor(vals.reduce((a, b) => a + b, 0) / vals.length)
      : 0;
    return { scores, findings, overall };
  }

  function analyze(systemPrompt) {
    return analyzeWithFindings(systemPrompt).scores;
  }

  function scoreTier(overall) {
    if (overall >= 90) return { n: "PRODUCTION READY", c: "score-green" };
    if (overall >= 70) return { n: "SHIP WITH MONITORING", c: "score-yellow" };
    if (overall >= 50) return { n: "NEEDS WORK", c: "score-orange" };
    return { n: "NOT PRODUCTION READY", c: "score-red" };
  }

  function vendorTier(overall) {
    if (overall >= 80) return { n: "TRUSTED", c: "score-green" };
    if (overall >= 50) return { n: "CAUTION", c: "score-yellow" };
    if (overall >= 30) return { n: "HIGH RISK", c: "score-orange" };
    return { n: "RED FLAG", c: "score-red" };
  }

  /** answers: array of 'yes'|'no'|'dk' — same points as CLI (y=10, dk=3, no=0). */
  function scoreVendor(answers) {
    const SCORE = { yes: 10, dk: 3, no: 0 };
    let total = 0;
    const redFlags = [];
    const critical = new Set(ENGINE.vendor_critical_keys);
    (answers || []).forEach((a, i) => {
      const norm = (a || "no").toLowerCase();
      const pts = SCORE[norm] !== undefined ? SCORE[norm] : 0;
      total += pts;
      const q = ENGINE.vendor_questions[i] || "";
      const key = ENGINE.vendor_keys[i] || "";
      if (norm === "no" || (norm === "dk" && critical.has(key))) {
        redFlags.push(q.replace(/\?$/, ""));
      }
    });
    return { score: total, tier: vendorTier(total), redFlags };
  }

  global.CrewScoreEngine = {
    ENGINE,
    analyze,
    analyzeWithFindings,
    scoreTier,
    vendorTier,
    scoreVendor,
    dimensions: ENGINE.dimensions,
    vendorQuestions: ENGINE.vendor_questions,
  };
})(typeof window !== "undefined" ? window : globalThis);
