"""Tests for offline configuration-smell detection (arXiv:2606.15828)."""

import shutil
import subprocess

import pytest

from crewscore.scoring import build_result
from crewscore.scorers.structural_analysis import analyze
from crewscore.smells import (
    CONTEXT_BLOAT_MAX_LINES,
    detect_context_bloat,
    detect_init_fossilization,
    detect_lint_leakage,
    detect_smells,
    find_repo_root,
)

STYLE_TEXT = """
# Project guide

Use single quotes for all strings. Maximum line length is 100 characters.
Imports should be sorted alphabetically. Run prettier before committing.
"""

NO_STYLE_TEXT = """
# Project guide

This service reconciles billing events against the ledger. Never mutate a
posted entry; issue a reversing entry instead.
"""


def _git(*args, cwd):
    subprocess.run(["git", *args], cwd=str(cwd), check=True, capture_output=True)


def _init_repo(path):
    _git("init", cwd=path)
    _git("config", "user.email", "test@example.com", cwd=path)
    _git("config", "user.name", "Test", cwd=path)


needs_git = pytest.mark.skipif(
    shutil.which("git") is None, reason="git not available"
)


# ─── Context Bloat ────────────────────────────────────────────────

def test_context_bloat_fires_at_threshold():
    text = "\n".join(f"line {i}" for i in range(CONTEXT_BLOAT_MAX_LINES))
    smell = detect_context_bloat(text)
    assert smell is not None
    assert smell["smell_id"] == "smell.context_bloat"
    assert smell["line_count"] == CONTEXT_BLOAT_MAX_LINES
    assert smell["affects_score"] is False
    assert "2606.15828" in smell["citation"]


def test_context_bloat_silent_below_threshold():
    text = "\n".join(f"line {i}" for i in range(CONTEXT_BLOAT_MAX_LINES - 1))
    assert detect_context_bloat(text) is None


def test_context_bloat_silent_on_empty():
    assert detect_context_bloat("") is None


# ─── Init Fossilization ───────────────────────────────────────────

@needs_git
def test_init_fossilization_fires_on_single_commit(tmp_path):
    _init_repo(tmp_path)
    agents = tmp_path / "AGENTS.md"
    agents.write_text("# Generated by init\n", encoding="utf-8")
    _git("add", "AGENTS.md", cwd=tmp_path)
    _git("commit", "-m", "init", cwd=tmp_path)

    smell = detect_init_fossilization(agents)
    assert smell is not None
    assert smell["smell_id"] == "smell.init_fossilization"
    assert smell["commit_count"] == 1


@needs_git
def test_init_fossilization_silent_after_revision(tmp_path):
    _init_repo(tmp_path)
    agents = tmp_path / "AGENTS.md"
    agents.write_text("# Generated by init\n", encoding="utf-8")
    _git("add", "AGENTS.md", cwd=tmp_path)
    _git("commit", "-m", "init", cwd=tmp_path)
    agents.write_text("# Generated by init\n\nRevised.\n", encoding="utf-8")
    _git("add", "AGENTS.md", cwd=tmp_path)
    _git("commit", "-m", "revise", cwd=tmp_path)

    assert detect_init_fossilization(agents) is None


@needs_git
def test_untracked_file_is_not_fossilized(tmp_path):
    """An unanswerable question must not look like a finding."""
    _init_repo(tmp_path)
    agents = tmp_path / "AGENTS.md"
    agents.write_text("# Never committed\n", encoding="utf-8")
    assert detect_init_fossilization(agents) is None


def test_init_fossilization_outside_repo_is_silent(tmp_path):
    agents = tmp_path / "AGENTS.md"
    agents.write_text("# No repo here\n", encoding="utf-8")
    assert detect_init_fossilization(agents) is None


def test_init_fossilization_handles_missing_path():
    assert detect_init_fossilization(None) is None
    assert detect_init_fossilization("/nonexistent/AGENTS.md") is None


# ─── Lint Leakage ─────────────────────────────────────────────────

def test_lint_leakage_needs_both_halves(tmp_path):
    (tmp_path / ".prettierrc").write_text("{}", encoding="utf-8")
    smell = detect_lint_leakage(STYLE_TEXT, tmp_path)
    assert smell is not None
    assert smell["smell_id"] == "smell.lint_leakage"
    assert ".prettierrc" in smell["linter_configs"]
    assert "quotes" in smell["style_topics"]
    # Honest about being narrower than the paper's LLM detector.
    assert smell["approximates_paper"] is True


def test_lint_leakage_silent_without_linter_config(tmp_path):
    """No config means nothing is duplicated — the file may be the only rule."""
    assert detect_lint_leakage(STYLE_TEXT, tmp_path) is None


def test_lint_leakage_silent_without_style_rules(tmp_path):
    (tmp_path / ".prettierrc").write_text("{}", encoding="utf-8")
    assert detect_lint_leakage(NO_STYLE_TEXT, tmp_path) is None


def test_lint_leakage_counts_configured_pyproject(tmp_path):
    (tmp_path / "pyproject.toml").write_text(
        "[tool.ruff]\nline-length = 100\n", encoding="utf-8"
    )
    smell = detect_lint_leakage(STYLE_TEXT, tmp_path)
    assert smell is not None
    assert "pyproject.toml" in smell["linter_configs"]


def test_bare_pyproject_is_not_a_linter_config(tmp_path):
    """A pyproject with no linter section configures no style tooling."""
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "x"\n', encoding="utf-8"
    )
    assert detect_lint_leakage(STYLE_TEXT, tmp_path) is None


# ─── Aggregation and score isolation ──────────────────────────────

@needs_git
def test_detect_smells_aggregates(tmp_path):
    _init_repo(tmp_path)
    (tmp_path / ".editorconfig").write_text("root = true\n", encoding="utf-8")
    agents = tmp_path / "AGENTS.md"
    body = STYLE_TEXT + "\n".join(f"line {i}" for i in range(CONTEXT_BLOAT_MAX_LINES))
    agents.write_text(body, encoding="utf-8")
    _git("add", ".", cwd=tmp_path)
    _git("commit", "-m", "init", cwd=tmp_path)

    found = {s["smell_id"] for s in detect_smells(body, path=agents, repo_root=tmp_path)}
    assert found == {
        "smell.context_bloat",
        "smell.init_fossilization",
        "smell.lint_leakage",
    }


def test_detect_smells_without_context_only_checks_text():
    """A --prompt string has no path or repo, so only Context Bloat can run."""
    body = "\n".join(f"line {i}" for i in range(CONTEXT_BLOAT_MAX_LINES))
    found = [s["smell_id"] for s in detect_smells(body)]
    assert found == ["smell.context_bloat"]


def test_smells_never_change_the_score():
    """Smells are advisory: they must not move the number CI thresholds on."""
    body = "\n".join(f"line {i}" for i in range(CONTEXT_BLOAT_MAX_LINES))
    smells = detect_smells(body)
    assert smells
    dimensions = analyze(body)
    with_smells = build_result(dimensions, prompt_text=body, smells=smells)
    without = build_result(dimensions, prompt_text=body)
    assert with_smells.overall == without.overall
    assert with_smells.tier == without.tier
    assert with_smells.to_dict()["smells"] == smells


def test_find_repo_root_locates_git_dir(tmp_path):
    (tmp_path / ".git").mkdir()
    nested = tmp_path / "a" / "b"
    nested.mkdir(parents=True)
    target = nested / "AGENTS.md"
    target.write_text("x", encoding="utf-8")
    assert find_repo_root(target) == tmp_path.resolve()


def test_find_repo_root_returns_none_outside_repo(tmp_path):
    assert find_repo_root(tmp_path / "AGENTS.md") is None
    assert find_repo_root(None) is None
