"""Configuration-smell detection — offline, deterministic, cited.

Implements the subset of the six configuration smells catalogued by
dos Santos, Costa, Montandon, Silva & Valente, *Configuration Smells in
AGENTS.md Files* (arXiv:2606.15828), that can be detected **without an LLM**.

The paper detects three of its six smells (Skill Leakage, Blind References,
Conflicting Instructions) with LLM prompts. CrewScore does not implement those:
it stays offline and deterministic, and it would rather ship three honest
detectors than six approximate ones.

    smell.context_bloat        >= 200 lines           paper heuristic, verbatim
    smell.init_fossilization   single commit          paper heuristic, verbatim
    smell.lint_leakage         style rules + linter   narrower approximation

**Lint Leakage is an approximation and is labelled as such.** The paper uses an
LLM to judge whether guidance duplicates existing tooling. CrewScore requires
two mechanical conditions instead: style-rule language in the file *and* a
linter/formatter config present in the repo. That is narrower than the paper's
detector — it will miss cases the paper catches. It does not invent an LLM
dependency to close the gap.

Smells are **advisory findings, not score deductions.** Folding them into the
0-100 number would silently change the meaning of every existing
`--threshold N` in a consumer's CI. Whether they should affect the score is a
question for corpus validation, not a decision to make quietly in a patch.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

__all__ = [
    "CITATION",
    "CONTEXT_BLOAT_MAX_LINES",
    "SMELL_CATALOG",
    "detect_smells",
    "detect_context_bloat",
    "detect_init_fossilization",
    "detect_lint_leakage",
    "find_repo_root",
]

CITATION = (
    "dos Santos et al., 'Configuration Smells in AGENTS.md Files' "
    "(arXiv:2606.15828)"
)

# The paper flags files at or over 200 lines; this matches Anthropic's own
# published guidance to keep a CLAUDE.md under 200 lines.
CONTEXT_BLOAT_MAX_LINES = 200

# Prevalence figures are the paper's, across 100 popular OSS projects.
SMELL_CATALOG: dict[str, dict[str, object]] = {
    "smell.context_bloat": {
        "name": "Context Bloat",
        "definition": (
            "File is large enough that rules, examples, and low-priority "
            "detail crowd out critical instructions and inflate token cost."
        ),
        "heuristic": f">= {CONTEXT_BLOAT_MAX_LINES} lines",
        "paper_prevalence": "42% of 100 popular OSS projects",
        "deterministic": True,
        "approximates_paper": False,
    },
    "smell.init_fossilization": {
        "name": "Init Fossilization",
        "definition": (
            "File was generated by an init command and never revised, so it "
            "accumulates instructions that no longer match the project."
        ),
        "heuristic": "tracked by git with exactly one commit",
        "paper_prevalence": "24% of 100 popular OSS projects",
        "deterministic": True,
        "approximates_paper": False,
    },
    "smell.lint_leakage": {
        "name": "Lint Leakage",
        "definition": (
            "File spends instruction budget on style rules a linter or "
            "formatter already enforces for free."
        ),
        "heuristic": (
            "style-rule language present AND a linter/formatter config exists "
            "in the repo (narrower than the paper's LLM detector)"
        ),
        "paper_prevalence": "62% of 100 popular OSS projects — the most common",
        "deterministic": True,
        "approximates_paper": True,
    },
}

# Style topics a linter/formatter owns. Deliberately conservative: each pattern
# has to look like a *rule about formatting*, not an incidental mention.
_STYLE_RULE_PATTERNS: list[tuple[str, str]] = [
    ("indentation", r"\b(?:use\s+)?(?:\d+[- ]space|tabs?\s+(?:not|over|instead)|spaces?\s+(?:not|over|instead))"),
    ("quotes", r"\b(?:single|double)\s+quotes?\b"),
    ("semicolons", r"\bsemicolons?\b"),
    ("line_length", r"\b(?:max(?:imum)?\s+line\s+length|line\s+length\s+(?:of|limit)|\d{2,3}\s*(?:char|column))"),
    ("import_order", r"\bimports?\s+(?:should\s+be\s+|must\s+be\s+)?(?:sorted|ordered|grouped|alphabetiz)"),
    ("trailing_whitespace", r"\btrailing\s+(?:whitespace|comma)"),
    ("formatting_tool", r"\b(?:run\s+)?(?:prettier|black|gofmt|rustfmt|biome|autopep8|yapf)\b"),
    ("naming_convention", r"\buse\s+(?:camelCase|snake_case|PascalCase|kebab-case)"),
]

# Config files that prove a linter/formatter already owns style in this repo.
_LINTER_CONFIG_GLOBS: list[str] = [
    ".eslintrc", ".eslintrc.*", "eslint.config.*",
    ".prettierrc", ".prettierrc.*", "prettier.config.*",
    ".editorconfig", "biome.json", "biome.jsonc",
    "ruff.toml", ".ruff.toml", ".flake8", "setup.cfg", "tox.ini",
    ".rubocop.yml", "rustfmt.toml", ".rustfmt.toml", ".golangci.yml",
    ".golangci.yaml", ".stylelintrc", ".stylelintrc.*",
]

# pyproject.toml only counts when it actually configures a formatter/linter.
_PYPROJECT_TOOL_SECTIONS = ("[tool.ruff", "[tool.black", "[tool.isort", "[tool.flake8")


def find_repo_root(path: str | Path | None) -> Path | None:
    """Nearest ancestor containing .git, or None outside a repo."""
    if not path:
        return None
    p = Path(path).resolve()
    if p.is_file():
        p = p.parent
    for candidate in [p, *p.parents]:
        if (candidate / ".git").exists():
            return candidate
    return None


def _smell(smell_id: str, detail: str, **extra: object) -> dict:
    meta = SMELL_CATALOG[smell_id]
    finding = {
        "smell_id": smell_id,
        "name": meta["name"],
        "detail": detail,
        "heuristic": meta["heuristic"],
        "paper_prevalence": meta["paper_prevalence"],
        "citation": CITATION,
        "deterministic": meta["deterministic"],
        "approximates_paper": meta["approximates_paper"],
        "affects_score": False,
    }
    finding.update(extra)
    return finding


def detect_context_bloat(text: str) -> dict | None:
    """Flag files at or over the published 200-line threshold."""
    if not text:
        return None
    lines = len(text.splitlines())
    if lines < CONTEXT_BLOAT_MAX_LINES:
        return None
    return _smell(
        "smell.context_bloat",
        f"{lines} lines (threshold {CONTEXT_BLOAT_MAX_LINES}). "
        "Long files raise token cost and reduce adherence to the rules that matter.",
        line_count=lines,
    )


def _git_commit_count(path: Path) -> int | None:
    """Commits touching `path`, capped at 2. None when git can't answer.

    Capped deliberately: the only question is "exactly one commit or more than
    one", so `-2` bounds the work regardless of how deep the history goes. A
    repo-wide scan runs this once per candidate file, and walking full history
    each time would dominate the scan.

    Returns None — never 0 — for every failure mode (git missing, not a repo,
    file untracked, shallow clone). An unanswerable question must not look
    like a finding.

    A shallow clone (e.g. actions/checkout's default fetch-depth: 1) makes
    `git log -2` exit 0 and return exactly one commit for every file,
    regardless of how many times the file was really revised in the
    un-truncated history. That single truncated commit must not be read as
    "never revised since creation".
    """
    try:
        shallow = subprocess.run(
            ["git", "rev-parse", "--is-shallow-repository"],
            cwd=str(path.parent),
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if shallow.returncode != 0:
        return None
    if shallow.stdout.strip() == "true":
        return None

    try:
        proc = subprocess.run(
            ["git", "log", "--follow", "--format=%H", "-2", "--", path.name],
            cwd=str(path.parent),
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if proc.returncode != 0:
        return None
    commits = [line for line in proc.stdout.splitlines() if line.strip()]
    if not commits:
        return None  # untracked — not evidence of fossilization
    return len(commits)


def detect_init_fossilization(path: str | Path | None) -> dict | None:
    """Flag a tracked file that has never been revised since it was created."""
    if not path:
        return None
    p = Path(path)
    if not p.exists():
        return None
    count = _git_commit_count(p)
    if count is None or count != 1:
        return None
    return _smell(
        "smell.init_fossilization",
        "Tracked by git with exactly one commit — never revised since creation. "
        "Init-generated guidance drifts out of date as the project moves.",
        commit_count=count,
    )


def _find_linter_configs(repo_root: Path) -> list[str]:
    found: list[str] = []
    for pattern in _LINTER_CONFIG_GLOBS:
        for match in repo_root.glob(pattern):
            if match.is_file():
                found.append(match.name)
    pyproject = repo_root / "pyproject.toml"
    if pyproject.is_file():
        try:
            content = pyproject.read_text(encoding="utf-8", errors="replace")
        except OSError:
            content = ""
        if any(section in content for section in _PYPROJECT_TOOL_SECTIONS):
            found.append("pyproject.toml")
    return sorted(set(found))


def detect_lint_leakage(text: str, repo_root: str | Path | None) -> dict | None:
    """Flag style guidance that a configured linter already enforces.

    Needs both halves: style-rule language in the file, and a linter/formatter
    config in the repo. Without a config there is nothing to duplicate, so
    style guidance in the file may be the only thing enforcing it.
    """
    if not text or not repo_root:
        return None
    root = Path(repo_root)
    if not root.is_dir():
        return None

    lowered = text.lower()
    topics = [
        topic
        for topic, pattern in _STYLE_RULE_PATTERNS
        if re.search(pattern, lowered, re.IGNORECASE)
    ]
    if not topics:
        return None

    configs = _find_linter_configs(root)
    if not configs:
        return None

    return _smell(
        "smell.lint_leakage",
        f"Style guidance ({', '.join(topics)}) duplicates tooling already "
        f"configured in this repo ({', '.join(configs)}). "
        "A pre-commit hook enforces this for free; instruction budget spent "
        "here is dead weight.",
        style_topics=topics,
        linter_configs=configs,
    )


def detect_smells(
    text: str,
    *,
    path: str | Path | None = None,
    repo_root: str | Path | None = None,
) -> list[dict]:
    """Run every offline smell detector that has enough context to run.

    Detectors that need context they weren't given stay silent rather than
    guessing: Context Bloat needs only the text, Init Fossilization needs a
    real path inside a git repo, Lint Leakage needs a repo root.
    """
    findings: list[dict] = []
    for finding in (
        detect_context_bloat(text),
        detect_init_fossilization(path),
        detect_lint_leakage(text, repo_root),
    ):
        if finding:
            findings.append(finding)
    return findings
